# Generated by Django 2.2.3 on 2020-03-29 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pk_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('reg_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Library')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_limit', models.IntegerField(default=10)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('reg_library', models.ForeignKey(help_text='Registered Library', on_delete=django.db.models.deletion.CASCADE, to='LMS.Library')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Category')),
            ],
            options={
                'verbose_name_plural': 'ISBNs',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='LMS.Staff'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('pk_num', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.ISBN')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Library')),
                ('taken_out', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='LMS.Member')),
            ],
        ),
    ]
