# Generated by Django 2.2.3 on 2020-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pk_num',
        ),
        migrations.AlterField(
            model_name='member',
            name='book_limit',
            field=models.IntegerField(default=10),
        ),
    ]
