# Generated by Django 2.2.3 on 2020-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20200309_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='isbn',
            options={'verbose_name_plural': 'ISBNs'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='book',
            name='taken_out',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='LMS.Member'),
        ),
    ]
