# Generated by Django 2.2.3 on 2020-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20200329_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loan_until',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
