# Generated by Django 2.2.3 on 2020-03-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20200322_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pk_num',
        ),
    ]
