# Generated by Django 2.2.3 on 2020-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_book_loan_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='back_in',
            field=models.BooleanField(default=True),
        ),
    ]
